spring.datasource.url=jdbc:postgresql://localhost:5432/outbox
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration - Auto-create the Outbox Table
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = create

# Show SQL in logs (Optional)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false